spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:dev.env[.properties]

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: jdbc:${DB_TYPE}://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

openvidu-url: ${OPEN_VIDU_URL}
openvidu-secret: ${OPEN_VIDU_SECRET}