spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.dev.env[.properties]

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}