# 쓰레드 풀
server:
  tomcat:
    threads:
      max: 200

spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:dev.env[.properties]

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: jdbc:${DB_TYPE}://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximumPoolSize: 60  # 최대 커넥션 수 (기본값 10)
      minimumIdle: 10       # 최소 유지 커넥션
      idleTimeout: 30000    # (30초) 사용하지 않는 커넥션 종료
      connectionTimeout: 30000  # (30초) 커넥션 대기 시간

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
        jdbc:
          batch_size: 50

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIEND_ID}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope: profile_nickname, profile_image
        provider:
          kakao: # registration 이름과 일치해야 함
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 사용자 정보에서 ID 추출 필드

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

openvidu-url: ${OPEN_VIDU_URL}
openvidu-secret: ${OPEN_VIDU_SECRET}

special-gift:
  open-day: ${SPECIAL_GIFT_OPEN_DAY}

jwt:
  secret: ${JWT_SECRET}

frontend-url: ${FRONTEND_URL}

scheduler:
  event-day-transition-cron: "0 */10 * * * *"